### ISSUE TITLE
Error after updating Vaadin from 7.4.2 to 7.4.4

### ISSUE THREAD

**Issue by russellhoff** [mstahv/v-leaflet#80]
After upgrading Vaadin from 7.4.2 to 7.4.4, the Google Maps Layer stopped working. This line 
mapa.addBaseLayer(new LGoogleLayer(Type.ROADMAP), "Google Maps"); (regardless the type of map you set Roadmap, Hybrid, Terrain...), the following exception is thrown:

java.lang.NoClassDefFoundError: org/vaadin/addon/leaflet/client/AbstractLeafletComponentState
	at com.ingartek.cavwebapp.view.administrador.verplan.ComponenteVerPlanMapa_DatosNuevos.setupMapaL(ComponenteVerPlanMapa_DatosNuevos.java:292)
	at com.ingartek.cavwebapp.view.administrador.verplan.ComponenteVerPlanMapa_DatosNuevos.<init>(ComponenteVerPlanMapa_DatosNuevos.java:156)
	at com.ingartek.cavwebapp.view.administrador.VerPlanView.inicializarParaPlan(VerPlanView.java:109)
	at com.ingartek.cavwebapp.view.administrador.VerPlanView.initLayout(VerPlanView.java:91)
	at com.ingartek.cavwebapp.view.administrador.VerPlanView.enter(VerPlanView.java:81)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:577)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526)
	at com.ingartek.cavwebapp.view.administrador.ComponenteHistoricoPlanes.lambda$0(ComponenteHistoricoPlanes.java:255)
	at com.ingartek.cavwebapp.view.administrador.ComponenteHistoricoPlanes$$Lambda$3/28041108.click(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:977)
	at com.vaadin.ui.renderers.ClickableRenderer.access$300(ClickableRenderer.java:40)
	at com.vaadin.ui.renderers.ClickableRenderer$1.click(ClickableRenderer.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:291)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:184)
	at com.vaadin.server.communication.PushHandler$3.run(PushHandler.java:176)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:255)
	at com.vaadin.server.communication.PushHandler.access$200(PushHandler.java:58)
	at com.vaadin.server.communication.PushHandler$1.onRequest(PushHandler.java:78)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:205)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:104)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:570)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:332)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:327)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:424)
	at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:206)
	at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:203)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:393)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:494)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:289)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:130)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:60)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:203)
	at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:194)
	at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:96)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.vaadin.addon.leaflet.client.AbstractLeafletComponentState
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	... 58 more

Before upgrading to 7.4.4 everything with Google Maps Layer worked correctly.

**Comment by mstahv** [comment]
Hi, I tried with 7.4.4 and v-leaflet: everything seemed to work just fine. I didn't yet try with Google layer, but the stack trace don't look like it could come from it. You could you try clean build again and let me know if the issue still exists.

**Comment by russellhoff** [comment]
Hi @mstahv, what do you mean by "clean build"? If you mean compiling theme and widgetset again and generating the WAR, I did so. And the problem still exists...

**Comment by russellhoff** [comment]
@mstahv The LOpenStreetMapLayer works fine.

**Comment by mstahv** [comment]
Then the issue must be in the Shramov extension: https://github.com/mstahv/v-leaflet-shramov-parent

I'll try find some time to look into this today.

**Comment by russellhoff** [comment]
I've realised that the AbstractLeafletComponentState class is localed on org.vaadin.addon.leaflet.shared, but it's looking for it into org.vaadin.addon.leaflet.client

**Comment by russellhoff** [comment]
@mstahv, I think I've found the bug. Let me solve it :)

**Comment by russellhoff** [comment]
I've created a pull request. Please tell me if it's enough.

**Comment by russellhoff** [comment]
AbstractLeafletComponentState class.

**Comment by mstahv** [comment]
Hi,

[This](https://github.com/russellhoff/v-leaflet-shramov-parent/commit/614493241797e834f6fa8dd84c8accc7223c80dd) seems to be the right change, I didn't find the pull request though. I think you should also change the dependency form pom.xml to to reflect to the latest version of v-leaflet (0.6.3).

cheers,
matti

**Comment by russellhoff** [comment]
Hi,

Can't see where to change the latest version of v-leaflet: do you mean the pom.xml of v-leaflet-shramov-parent root or the pom.xml from v-leaflet-shramov?

**Comment by mstahv** [comment]
Here:
https://github.com/russellhoff/v-leaflet-shramov-parent/blob/master/v-leaflet-shramov/pom.xml#L11

The Vaadin version against it is compiled and tested could also be upgraded.

**Comment by russellhoff** [comment]
Thanks! I think it's updated :)

**Comment by mstahv** [comment]
Looks perfect now, will you make pull request or shall I pick the changes manually?

**Comment by russellhoff** [comment]
I'm trying to learn how to make a pull request... Sorry for opening two...

**Comment by mstahv** [comment]
No problem. Big thanks for your contribution. I'll look into another leaflet issue later today and build a new release during the weekend at latest!

**Comment by mstahv** [comment]
0.0.3 version of v-leaflet-shramov should be now available via vaadin.com/directory

Let me know if you have any issues with it!
